### ISSUE TITLE
how to represent GC seq and gc percentage in TAB file?

### ISSUE THREAD

**Issue by Unlock-ViV** [paulstothard/cgview#1]
I want to represent GC skew and GC percentage in the final plot, but I'm not able to understand how and were in the (column) file i have to make changes. can you please tell me how to do it using a tab file. I have calculated the GC skew using[ SkewIT ](https://github.com/jenniferlu717/SkewIT). 
![skew](https://user-images.githubusercontent.com/56451047/87946789-1a2e6080-cac0-11ea-8e32-a03c5a08f64f.PNG)
![cgvies](https://user-images.githubusercontent.com/56451047/87946809-21556e80-cac0-11ea-93a0-8bbaefbd5bcf.PNG)

**Comment by paulstothard** [comment]
You can use the included cgview_xml_builder.pl script to generate the GC and GC skew plots.

The following uses the Docker image to generate a map for NC_017030 showing the plots as calculated using a sliding window of 20000 bp:

docker pull pstothard/cgview

CGVIEW="docker run --rm -v $(pwd):/dir -w /dir pstothard/cgview"

$CGVIEW perl /usr/bin/cgview_xml_builder.pl -sequence NC_017030.gbk -gc_content T -gc_skew T -size large-v2 -tick_density 0.05 -draw_divider_rings T -custom showBorder=false window=20000 title="Corallococcus coralloides DSM 2259" titleFontSize="200" -output NC_017030.xml

$CGVIEW java -jar /usr/bin/cgview.jar -i NC_017030.xml -o NC_017030.png

![NC_017030](https://user-images.githubusercontent.com/50184499/87958919-5be2eb00-ca6f-11ea-986d-c8e3ef6384b2.png)

**Comment by Unlock-ViV** [comment]
but is this thing is not possible for tab file? Because the reason is I have some very selective features to represent along with the representation you have given, and those may or may not be present in the GenBank file. That's why only to represent those features I have used the tab file as they are not derived from GenBank file. please the attached file tab file.

I want to embed the features of the below plot along with the plot that you have generated. That is where I'm struck.
![cgview-FULL](https://user-images.githubusercontent.com/56451047/87961219-0b04de00-cad3-11ea-8f0b-2004091cc4bd.png)



[cgview_plot_file.zip](https://github.com/paulstothard/cgview/files/4948832/cgview_plot_file.zip)

**Comment by paulstothard** [comment]
You can hide the features from the GenBank file using:

-show_sequence_features F

And then add your own features (in this case in a file called features.tab) as follows:

-genes features.tab

The features.tab file should be formatted as follows:

<img width="544" alt="image" src="https://user-images.githubusercontent.com/50184499/87969456-6b6a3000-ca7f-11ea-9c03-bf31370e4c6d.png">

The complete commands to run are:
CGVIEW="docker run --rm -v $(pwd):/dir -w /dir pstothard/cgview"

$CGVIEW perl /usr/bin/cgview_xml_builder.pl -sequence NC_017030.gbk -show_sequence_features F -genes features.tab -gene_labels T -gene_decoration arc -gc_content T -gc_skew T -size large-v2 -tick_density 0.05 -draw_divider_rings T -custom showBorder=false window=20000 backboneRadius=3000 useInnerLabels=false title="Corallococcus coralloides DSM 2259" titleFontSize="200" width=14000 height=14000 labelFontSize=100 -output NC_017030v2.xml

$CGVIEW java -Xmx2G -jar /usr/bin/cgview.jar -i NC_017030v2.xml -o NC_017030v2.png

![NC_017030v2](https://user-images.githubusercontent.com/50184499/87969663-cac84000-ca7f-11ea-80cd-11103b7f265b.png)

**Comment by Unlock-ViV** [comment]
ohh wao.. it nicely works. thank you very much.

**Comment by Unlock-ViV** [comment]
is docker is necessary? (docker pull pstothard/cgview)  to  run the above commands?

**Comment by paulstothard** [comment]
Those sample commands do require Docker but can be easily modified to work without Docker, e.g.: 

perl /usr/bin/cgview_xml_builder.pl -sequence NC_017030.gbk -show_sequence_features F -genes features.tab -gene_labels T -gene_decoration arc -gc_content T -gc_skew T -size large-v2 -tick_density 0.05 -draw_divider_rings T -custom showBorder=false window=20000 backboneRadius=3000 useInnerLabels=false title="Corallococcus coralloides DSM 2259" titleFontSize="200" width=14000 height=14000 labelFontSize=100 -output NC_017030v2.xml

java -Xmx2G -jar /usr/bin/cgview.jar -i NC_017030v2.xml -o NC_017030v2.png

**Comment by Unlock-ViV** [comment]
okay I'll try it.  thank you so much
