### ISSUE TITLE
CGView installations fails

### ISSUE THREAD

**Issue by vkk24** [paulstothard/cgview#2]
While building cgview.jar file using build.sh , the following error is encountered:

`[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.480s
[INFO] Finished at: Wed Feb 24 16:26:15 IST 2021
[INFO] Final Memory: 23M/1214M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:jar (attach-javadocs) on project cgview: Unable to parse configuration of mojo org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:jar for parameter additionalOptions: Cannot assign configuration entry 'additionalOptions' with value '-Xdoclint:none' of type java.lang.String to property of type java.lang.String[] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginConfigurationException
`

I tried deleting .m2/repository using :
`rm -rf ~/.m2/repository`

But still the same error occurs.
Please guide in this regards.

My java version is:
`openjdk version "1.8.0_152-release"
OpenJDK Runtime Environment (build 1.8.0_152-release-1056-b12)
OpenJDK 64-Bit Server VM (build 25.152-b12, mixed mode)`

Thanks.

**Comment by paulstothard** [comment]
Hello,

Can you edit the pom.xml file to remove these lines:

```
<additionalOptions>-Xdoclint:none</additionalOptions>
<additionalJOption>-Xdoclint:none</additionalJOption>
```

And then re-run the build script?

Paul

**Comment by vkk24** [comment]
Hi @paulstothard ,
Thanks for your quick reply.

I edited the pom.xml file as you suggested. But now its giving me this error:

`[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28.176s
[INFO] Finished at: Thu Feb 25 16:19:36 IST 2021
[INFO] Final Memory: 16M/559M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project cgview: An exception occured while executing the Java class. null: NullPointerException -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`



Debug logging :

`Apache Maven 3.0.5 (Red Hat 3.0.5-17)
Maven home: /usr/share/maven
Java version: 1.8.0_152-release, vendor: JetBrains s.r.o
Java home: /home/groupA/anaconda3/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1127.19.1.el7.x86_64", arch: "amd64", family: "unix"
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /usr/share/maven/conf/settings.xml
[DEBUG] Reading user settings from /home/groupA/.m2/settings.xml
[DEBUG] Using local repository at /home/groupA/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10 for /home/groupA/.m2/repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project ca.ualberta.stothard.cgview:cgview:jar:2.0.2-SNAPSHOT: (none)
[DEBUG] Looking up lifecyle mappings for packaging jar from ClassRealm[plexus.core, parent: null]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.079s
[INFO] Finished at: Thu Feb 25 17:06:52 IST 2021
[INFO] Final Memory: 13M/962M
[INFO] ------------------------------------------------------------------------
[ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-site, site, post-site, site-deploy, pre-clean, clean, post-clean. -> [Help 1]
org.apache.maven.lifecycle.NoGoalSpecifiedException: No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-site, site, post-site, site-deploy, pre-clean, clean, post-clean.
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:104)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoGoalSpecifiedException
`

My pom.xml file after editing:
[pom.txt](https://github.com/paulstothard/cgview/files/6040894/pom.txt)



-VK

**Comment by paulstothard** [comment]
I'm not sure then what is causing the issue. Your revised pom file works on my system.

My only other suggestions would be to update Maven and Java.

If you aren't editing the CGView code then I suggest downloading the pre-built jar directly:

https://github.com/paulstothard/cgview/releases/tag/v2.0.2

Paul

**Comment by vkk24** [comment]
Thanks @paulstothard 
Updating Maven and Java worked!
Also needed to install JDK to install it successfully.
