### ISSUE TITLE
Visualize COGs

### ISSUE THREAD

**Issue by vappiah** [paulstothard/cgview#3]
Hi @paulstothard , I would be grateful If you can describe how to visualize COGs using the online CGVIew server tool. 

Thanks

**Comment by paulstothard** [comment]
Hello,

At this time there isn't a server version of CGView that supports COG visualization. However the CGView Comparison Tool can assign and display COGs:

https://github.com/paulstothard/cgview_comparison_tool

See the example here:

https://github.com/paulstothard/cgview_comparison_tool#using-the-cct-docker-image
