### ISSUE TITLE
CGView.jar applet

### ISSUE THREAD

**Issue by amvarani** [paulstothard/cgview#4]
Hi there,
Is there any way to still use the Tab files normally used with the old CGView applet to generate HTML page containing the maps and links  ?

**Comment by paulstothard** [comment]
Yes you can use the tab input with cgview.jar to generate HTML output. There is an example tab input file [here](https://github.com/paulstothard/cgview/blob/master/sample_input/tab/example_2.tab)

To generate the html page you can use:

`java -jar cgview.jar -i example_2.tab -f png -o map.png -h map.html`

To get the mouseovers working, add an includes directory containing [overlib.js](https://github.com/paulstothard/cgview/blob/master/src/main/resources/includes/overlib.js) to the same directory as map.html.
