### ISSUE TITLE
How to create a map from a genome with multiple contigs?

### ISSUE THREAD

**Issue by NuruddinKhoiry** [paulstothard/cgview#7]
Hi,

I am a newbie in this field. I would like to draw a genome map. My genome is at scaffold level with many contigs (59 contigs). After I annotated with Prokka I got an output.gbk file.  However, in the output.gbk file, there are many gbk files inside the file due to many contigs. I have tried to run:
1. cgview_xml_builder.pl -sequence output.gbk -output output.xml
2. cgview -i output.xml -o output.png -f png

From this command, I got a map from the first contig only. 
Would you please guide me on how I can solve this?

Thank you

**Comment by paulstothard** [comment]
Hello,

The software is designed to handle multi-contig input files, so I'm not sure what the issue is. Can you provide your input file?

A sample multi-contig file that I use for testing is available at:

https://paulstothard.github.io/cgview/downloads/prokka_multicontig.gbk

Paul

**Comment by NuruddinKhoiry** [comment]
Dear Paul,

Thank you for your response. 

I have tried to run the program using your file [prokka_multicontig.gbk](https://paulstothard.github.io/cgview/downloads/prokka_multicontig.gbk) as an input. I ran it using the following commands:

1. cgview_xml_builder.pl -sequence prokka_multicontig.gbk -output output.xml
2. cgview -i output.xml -o output.png -f png

I got the same problem as I have mentioned above. The program drew only from the first contig.

I installed the cgview (version 1.0) program using conda.

Here I attached the output files and "cgview_xml_builder.pl" script that I used to run it
[cgview.zip](https://github.com/paulstothard/cgview/files/9127043/cgview.zip)
.

Best regards,
Khoiri

**Comment by paulstothard** [comment]
Unfortunately the version obtained using conda (I didn't make the conda cgview package) doesn't support multi-contig input. Instead I recommend using the most up-to-date version of cgview via Docker, using commands like those used here:

https://github.com/paulstothard/cgview#using-the-cgview-docker-image
